// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type InstrumentStatusItem struct {
	TsCode          string `json:"tsCode"`
	Name            string `json:"name"`
	SyncEnabled     bool   `json:"syncEnabled"`
	LatestTradeDate string `json:"latestTradeDate"`
	LatestAdjDate   string `json:"latestAdjDate"`
	DailyRows       int    `json:"dailyRows"`
	AdjRows         int    `json:"adjRows"`
}

type PingResp struct {
	Message string `json:"message"`
}

type StatusResp struct {
	Instruments []InstrumentStatusItem `json:"instruments"`
}

type SyncReq struct {
	TsCodes []string `json:"tsCodes,optional"`
}

type SyncResp struct {
	Total   int              `json:"total"`
	Success int              `json:"success"`
	Results []SyncResultItem `json:"results"`
}

type SyncResultItem struct {
	TsCode        string `json:"tsCode"`
	StartDate     string `json:"startDate"`
	EndDate       string `json:"endDate"`
	Fetched       int    `json:"fetched"`
	Upserted      int    `json:"upserted"`
	DailyFetched  int    `json:"dailyFetched"`
	AdjFetched    int    `json:"adjFetched"`
	DailyUpserted int    `json:"dailyUpserted"`
	AdjUpserted   int    `json:"adjUpserted"`
	Message       string `json:"message"`
}
