// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type InstrumentStatusItem struct {
	TsCode          string `json:"tsCode"`
	Name            string `json:"name"`
	SyncEnabled     bool   `json:"syncEnabled"`
	LatestTradeDate string `json:"latestTradeDate"`
	LatestAdjDate   string `json:"latestAdjDate"`
	DailyRows       int    `json:"dailyRows"`
	AdjRows         int    `json:"adjRows"`
}

type PingResp struct {
	Message string `json:"message"`
}

type StatusResp struct {
	Instruments []InstrumentStatusItem `json:"instruments"`
}

type SyncReq struct {
	TsCodes []string `json:"tsCodes,optional"`
}

type SyncResp struct {
	Total   int              `json:"total"`
	Success int              `json:"success"`
	Results []SyncResultItem `json:"results"`
}

type SyncResultItem struct {
	TsCode        string `json:"tsCode"`
	StartDate     string `json:"startDate"`
	EndDate       string `json:"endDate"`
	Fetched       int    `json:"fetched"`
	Upserted      int    `json:"upserted"`
	DailyFetched  int    `json:"dailyFetched"`
	AdjFetched    int    `json:"adjFetched"`
	DailyUpserted int    `json:"dailyUpserted"`
	AdjUpserted   int    `json:"adjUpserted"`
	Message       string `json:"message"`
}

// SignalCardItem 是单个标的的盘中信号卡片（Signal Card）。
// Score/YZVol/Quantile 历史不足时为 NaN，JSON 层序列化为 null（指针 nil）。
type SignalCardItem struct {
	TsCode   string   `json:"tsCode"`
	Name     string   `json:"name"`
	Score    *float64 `json:"score"`
	YZVol    *float64 `json:"yzVol"`
	Quantile *float64 `json:"quantile"`
	Weight   float64  `json:"weight"`
	Rank     int      `json:"rank"`
	Stale    bool     `json:"stale"`
	Message  string   `json:"message"`
}

// AdviceItem 是单一持仓情形下的操作建议（Signal Card 建议表的一行）；
// TargetWeight 为 null 表示不下单或维持当前仓位不动。
type AdviceItem struct {
	Scenario     string   `json:"scenario"`
	Action       string   `json:"action"`
	TargetWeight *float64 `json:"targetWeight"`
	Note         string   `json:"note"`
}

type SignalResp struct {
	TradeDate string `json:"tradeDate"`
	// SnapshotDate 盘中快照交易日（YYYYMMDD）；与 TradeDate 不一致即非交易日。
	SnapshotDate string `json:"snapshotDate"`
	// TradingDay 为 false 表示非交易日（快照交易日 ≠ 今天），调用方应短路不推送。
	TradingDay bool             `json:"tradingDay"`
	Cards      []SignalCardItem `json:"cards"`
	// Advice 是五情形交易建议（现金 + 各标的），由 core.ComputeAdvice 从 Cards 推导。
	Advice []AdviceItem `json:"advice"`
}

// DiffField 单字段差值（官方日线 − 盘中快照）：Abs 绝对差，Bps 相对差（万分之一，快照为基准）。
type DiffField struct {
	Abs float64 `json:"abs"`
	Bps float64 `json:"bps"`
}

// SlippageDiffItem 单标的滑点差值（Slippage Diff）；
// Available=false（当日官方日线或盘中快照缺失）时各差值字段为 null，Message 记原因。
type SlippageDiffItem struct {
	TsCode    string     `json:"tsCode"`
	Name      string     `json:"name"`
	Available bool       `json:"available"`
	Open      *DiffField `json:"open"`
	High      *DiffField `json:"high"`
	Low       *DiffField `json:"low"`
	Close     *DiffField `json:"close"`
	MeanBps   *float64   `json:"meanBps"`
	Message   string     `json:"message"`
}

// CloseReportResp 收盘日报（Close Report）：同步摘要 + 滑点差值 + 官方收盘重算卡片。
// TradingDay 表示同步后当日官方日线已就位；HasSnapshot 表示当日盘中快照存在；
// 任一为 false 时调用方应降级为纯同步摘要（差值与重算无意义）。
type CloseReportResp struct {
	TradeDate   string             `json:"tradeDate"`
	TradingDay  bool               `json:"tradingDay"`
	HasSnapshot bool               `json:"hasSnapshot"`
	Sync        SyncResp           `json:"sync"`
	Diffs       []SlippageDiffItem `json:"diffs"`
	Cards       []SignalCardItem   `json:"cards"`
}
