// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	"syncer/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/ping",
				Handler: PingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/sync/etf-daily",
				Handler: SyncEtfDailyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/sync/status",
				Handler: SyncStatusHandler(serverCtx),
			},
		},
	)
}
